### ISSUE TITLE
Binlist.net SSL Certificate Distrusted in Chrome M70

### ISSUE THREAD

**Issue by payments-developer** [binlist/www#5]
When hitting binlist's api the following warning occurs within the chrome developer window:

The SSL certificate used to load resources from https://binlist.net will be distrusted very soon. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.

**Comment by tjconcept** [comment]
Thanks for the heads up! It has now been rolled.
